import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Genshin Vision Guide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${dmSans.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <header></header>
          <main className="flex flex-col flex-1">
            {children}
          </main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
