import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar/AppSidebar"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Genshin Vision Guide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar />

          <div className="flex flex-col min-h-screen">
            <main className="flex flex-col flex-1">
              {children}
            </main>
            <footer></footer>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
